[Version]
rocksdb_version=6.2.2

[DBOptions]
use_direct_reads=false
use_direct_io_for_flush_and_compaction=true
create_if_missing=true
max_open_files=-1
max_background_jobs=16
max_subcompactions=8
create_missing_column_families=true

[CFOptions "default"]
compression=kNoCompression
bottommost_compression=kNoCompression
compaction_style=kCompactionStyleLevel
level_compaction_dynamic_level_bytes=false
compaction_pri=kOldestLargestSeqFirst
write_buffer_size=33554432
max_write_buffer_number=10
min_write_buffer_number_to_merge=1
level0_file_num_compaction_trigger=4
level0_slowdown_writes_trigger=40
level0_stop_writes_trigger=64
max_bytes_for_level_base=134217728
max_bytes_for_level_multiplier=4
target_file_size_base=33554432
target_file_size_multiplier=1

[TableOptions/BlockBasedTable "default"]
no_block_cache=true
#block_cache_size=8589934592

[CFOptions "usertable"]
compression=kNoCompression
bottommost_compression=kNoCompression
compaction_style=kCompactionStyleLevel
level_compaction_dynamic_level_bytes=false
compaction_pri=kOldestLargestSeqFirst
write_buffer_size=33554432
max_write_buffer_number=10
min_write_buffer_number_to_merge=1
level0_file_num_compaction_trigger=4
level0_slowdown_writes_trigger=40
level0_stop_writes_trigger=64
max_bytes_for_level_base=134217728
max_bytes_for_level_multiplier=4
target_file_size_base=33554432
target_file_size_multiplier=1

[TableOptions/BlockBasedTable "usertable"]
no_block_cache=true
#block_cache_size=8589934592